### ISSUE TITLE
Improve Readme/first impression

### ISSUE THREAD

**Issue by krzychukula** [Schibsted-Tech-Polska/nodesi#1]
I really like the project but first impression when I show it to someone else is rather weak. If you find enough time it would be great if you can provide simple working demo that will be linked from the readme or url part of the project description.
Based on the readme it's really hard to tell what problem it really solves, or in which context to use it.

**Comment by kjarmicki** [comment]
Well there's really not much to it, it's just a subset of ESI spec implemented in Node ;) but ok, I'll think about it.

**Comment by kjarmicki** [comment]
@krzychukula I've added [use cases section](https://github.com/Schibsted-Tech-Polska/nodesi#what-problem-does-it-solve) to the readme. Better late than never I guess 😄

**Comment by krzychukula** [comment]
🍾  🎊  👍  :-)
