### ISSUE TITLE
Support onerror attribute

### ISSUE THREAD

**Issue by trieloff** [Schibsted-Tech-Polska/nodesi#23]
From [our favorite spec](https://www.w3.org/TR/esi-lang):

> If an ESI Processor can fetch neither the `src` nor the `alt`, it returns a HTTP status code greater than 400 with an error message, unless the `onerror` attribute is present. If it is, and `onerror="continue"` is specified, ESI Processors will delete the include element silently.

I'd like to add support for the `onerror` attribute, but in a way that does not break compatibility. Right now, nodesi by default behaves as if `onerror="continue"` was always set, unless an `onError` function is set in `options`.

I'd propose following changes:

1. the `onError` property in `options` can have the `string` value `strict`, in which case the error handling would happen according to spec:
  1.a. if `onerror="continue"`, behave as is
  2.b. if the `src` or `alt` can be retrieved with, behave as is
  3.c. if `src` (and `alt`) fails, fail the entire request with the same status as the `src` or `alt` request failed. – this makes it a bit easier to do troubleshooting, as the status of the failing resource is passed through.
2. the `onError` property in `options` can have an integer value, in which case the error handling would also happen according to spec, just like (1), but instead of responding in case (c) with the status code of the first failed request, it would respond with the specified integer value.

This gives users following options:
- if you like the current behavior, leave things as they are
- if you want ESI to fail with traceable errors, set `onError: 'strict'` and see the failing status code passed through
- if you want to stay as close to the HTTP spec as possible, set `onError: 502` and get "bad gateway" errors when the ESI processor cannot fetch.

**Comment by filipgolonka** [comment]
Sounds good. I'd suggest two enhancements to this approach:
* make sure the behavior is properly documented
* if `src` and `alt` fails, fail the entire request and throw `alt` error ennhanced with `src` error, so tracing will be much easier

**Comment by trieloff** [comment]
Good points. We should probably change the function signature to:

`onError: function(src, error, onerror, alt, origerror)` with
- `onerror` value of the `onerror` attribute or `undefined`
- `alt` value of the `alt` attribute or `undefined`
- `origerror` value of the original error when fetching `src`. Is only set when `alt` was set and failed

I'll submit a PR for the missing `alt` documentation right away.

**Comment by filipgolonka** [comment]
@trieloff I assume this can be closed?
