### ISSUE TITLE
<esi:remove> tags are not removed

### ISSUE THREAD

**Issue by kptdobe** [Schibsted-Tech-Polska/nodesi#27]
Reading the [spec](https://www.w3.org/TR/esi-lang) and since whole point of the current module is to "support ESI", I think the implementation of the spec here should be reduced to simply remove the `<esi:remove>` tags from the DOM. 

We need this for https://github.com/adobe/helix-simulator/issues/292.

I'll make a PR.

**Comment by kptdobe** [comment]
Actually... `if ESI processing is not enabled` may also be in the case the include tries to get an non existing resource. 
WDYT ?

**Comment by filipgolonka** [comment]
Sounds good!

**Comment by kptdobe** [comment]
I tested with Fastly and the behavior is like this:
- if included resource exists, content of resource included, no ESI output: `<esi:include/>` and `<esi:remove/>` stripped out
- if included resource does not exist, no output: `<esi:include/>` and `<esi:remove/>` stripped out
- if ESI disabled in Fastly config, tags stay in the DOM and browser display whatever is in the <esi:remove/> tag.

Example from Akamai seems to indicate the same behavior.

Conclusion for this module: whenever an `<esi:include/>` tag is processed, the following `<esi:remove/>` must be removed.

Working on the PR now.

**Comment by filipgolonka** [comment]
Closed by #28
