### ISSUE TITLE
Which esi tags are supported?

### ISSUE THREAD

**Issue by oskbor** [Schibsted-Tech-Polska/nodesi#29]
Hi,
in you readme you have this sentence

> nodesi does not support the entire ESI spec, but aims to provide a usable subset. 

Which tags besides `esi:include` are supported? It would be great if they were listed in the readme.

thanks in advance
 Oskar

**Comment by bukowskiadam** [comment]
Answering the question:
- `esi:include` - with `src` and `alt` attributes pointing to remote resources as stated in the Readme.
- `esi:remove` - it is just removed from the output - I'm not sure if it's useful 🤷🏻‍♂️ 
If that info is not enough then I recommend reading the test file: https://github.com/Schibsted-Tech-Polska/nodesi/blob/master/test/e2e-test.js
