### ISSUE TITLE
Support Buffer type in res.send() for text content

### ISSUE THREAD

**Issue by dominique-pfister** [Schibsted-Tech-Polska/nodesi#30]
We have a use-case where we pass a Buffer containing `esi` tags to res.send() down the chain. nodesi currently doesn't support that type, in its `middleware.js` res.send() implementation. 

I'll create a PR shortly to support it.

**Comment by filipgolonka** [comment]
@dominique-pfister thanks for reporting! I'm looking forward to see the PR!

**Comment by dominique-pfister** [comment]
Wow, what a fast resolution, thanks @filipgolonka !

**Comment by filipgolonka** [comment]
@dominique-pfister new version is now released in npm (1.13.0)
