### ISSUE TITLE
Bump 

### ISSUE THREAD

**Issue by blazbla274** [Schibsted-Tech-Polska/nodesi#48]
Hello Guys,

is there any possibility to replace `good-guy-http` to some other package which dependency is not based on depreciated and unsupported packages?

Thank you for your time :)

**Comment by bukowskiadam** [comment]
Hi there,

We know that good guy is not up to date and triggers some npm warnings, however, we do not have time at the moment to jump into the project and make some bigger changes. PR's are welcome. Btw did you know that you can provide your own httpClient in the config? Just make sure that it has the same API as good-guy 😉 . See more details here: https://github.com/Schibsted-Tech-Polska/nodesi/blob/master/lib/data-provider.js#L13

Best regards,
Adam

**Comment by bukowskiadam** [comment]
🎉 Done! https://github.com/Schibsted-Tech-Polska/nodesi/releases/tag/v2.0.0
