### ISSUE TITLE
Security Issue: Prototype Pollution in Ajv

### ISSUE THREAD

**Issue by GowsKJL93** [Schibsted-Tech-Polska/nodesi#49]
When running the `audit-ci` package to check for vulnerabilities it currently returns a moderate level issue which can be found here related to the version of the `ajv` package used:

https://github.com/advisories/GHSA-v88g-cgmw-v5xw

This should be resolvable by updating the version of `ajv` used

**Comment by bukowskiadam** [comment]
🎉 Fixed with v2.0 https://github.com/Schibsted-Tech-Polska/nodesi/releases/tag/v2.0.0
