### ISSUE TITLE
Security Issue: Server-Side Request Forgery in Request

### ISSUE THREAD

**Issue by GowsKJL93** [Schibsted-Tech-Polska/nodesi#50]
When running the audit-ci package to check for vulnerabilities it currently returns a moderate level issue which can be found here related to the `request` package used:

https://github.com/advisories/GHSA-p8p7-x288-28g6

Unfortunately the request package has been deprecated (https://www.npmjs.com/package/request)

**Comment by bukowskiadam** [comment]
Fixed with v2.0 https://github.com/Schibsted-Tech-Polska/nodesi/releases/tag/v2.0.0
