### ISSUE TITLE
Security Issue: tough-cookie Prototype Pollution vulnerability

### ISSUE THREAD

**Issue by GowsKJL93** [Schibsted-Tech-Polska/nodesi#51]
When running the audit-ci package to check for vulnerabilities it currently returns a moderate level issue which can be found here related to the `tough-cookie` package used:

[GHSA-72xf-g2v4-qvf3](https://github.com/advisories/GHSA-72xf-g2v4-qvf3)

This has been patched in higher versions.

**Comment by aaronclong** [comment]
Is there any plans to update these deps?

**Comment by bukowskiadam** [comment]
Hi there! Updating deps will not help here. We have to get rid of the built-in good-guy-http and some other dev dependency. I'll merge this PR #52 to bump deps, but I'll also work on the next step, which is removing the good-guy-http dependency -> so this will be a breaking change that will require you to provide a http client.

**Comment by bukowskiadam** [comment]
🎉 Fixed with v2.0 - https://github.com/Schibsted-Tech-Polska/nodesi/releases/tag/v2.0.0
