### ISSUE TITLE
Allowed hosts does not support regular expressions as documentation shows

### ISSUE THREAD

**Issue by iphands** [Schibsted-Tech-Polska/nodesi#6]
When I say:
```javascript
new ESI({
  allowedHosts: ['https://exact-host:3000', /^http(s)?:\/\/test.lan$/],
...
```
I can see the following line fail to `new AllowedHosts(config, logger);` with the config.
https://github.com/Schibsted-Tech-Polska/nodesi/blob/master/lib/esi.js#L14

I think that line should check Array.isArray(config.allowedHosts)... right?

**Comment by kjarmicki** [comment]
Hey @iphands 
Thank you for reporting an issue and creating PR :) I'm currently on holidays but I'll be able to review and merge your stuff next week. Cheers!

**Comment by iphands** [comment]
Awesome, thank you!
